In [4]:
import numpy as np
import scipy.optimize as opt

Ejercicio 1

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de análisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estándares nutricionales. Los requisitos que se tienen es que en 100 gramos, se deben tener por lo menos 9 gramos de proteína y  7 gramos de grasa. Así mismo, no se debe tener más de 2.5 gramos de fibra y 0.5 gramos de sal.

Ingrediente	Proteína	Grasa	Fibra	Sal
Pollo	10.0%	08.0%	00.1%	00.2%
Carne	20.0%	10.0%	00.5%	00.5%
Cordero	15.0%	11.0%	00.5%	00.7%
Arroz	00.0%	01.0%	10.0%	00.2%
Trigo	04.0%	01.0%	15.0%	00.8%
Gel	00.0%	00.0%	00.0%	00.0%
Los costos de cada producto son:

Ingrediente	Costo por gramo
Pollo	$0.012
Carne	$0.009
Cordero	$0.010
Arroz	$0.003
Trigo	$0.005
Gel	$0.002
Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total.

Paso 1: Minimizar costo

Paso 2: Gramos de producto

Paso 3: 

0.012x1 + 0.09x2, 0.01x3, 0.03x4, 0.005x5, 0.002x6
x1= Pollo, x2= Carne, x3=Cordero, x4=Arroz, x5=Trigo, x6=Gel

Paso 4:

0.10x1 + 0.2x2 + 0.15x3 + 0.04x5 $\geq$ 9

0.08x1 +  0.1x2 + 0.11x3 + 0.01x4 + 0.01x5 $\geq$ 7

0.01x1 + 0.05x2 + 0.05x3 + 0.1x4 + 0.15x5 $\leq$ 2.5 

0.02x1 + 0.05x2 + 0.07x3 + 0.02x4 + 0.08x5 $\leq$ 0.5


In [12]:
c = np.array([0.6, 0.2])

Aub = np.array([
    [-0.30, -0.05],
    [-0.01, -0.07],
    [-0.10, -0.10]
])

bub = np.array([-25, -6, -30])

import scipy.optimize as opt

opt.linprog(c, Aub, bub)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 76.0
              x: [ 4.000e+01  2.600e+02]
            nit: 2
          lower:  residual: [ 4.000e+01  2.600e+02]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.260e+01  0.000e+00]
                 marginals: [-1.600e+00 -0.000e+00 -1.200e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

Ejercicio 2

La Comisión Federal de Electricidad (CFE) dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas 1, 2 y 3 pueden satisfacer 75, 50 y 60 millones de kW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de 60, 45 y 60 millones de Kw al día respectivamente.

Los costos asociados al envío de suministro energético por cada millón de kW entre cada planta y cada ciudad son los registrados en la siguiente tabl

-	Guadalajara	León	Morelia
Planta 1	5	2	7
Planta 2	3	4	5
Planta 3	5	2	3

Paso 1: Minimizar costo de logística

Paso 2: ¿Que controlo? Cuánto se envía de una planta a la ciudad

x1G x1L x1M

x2G x2L x2M

x3G x3L x3M

Paso 3: 5x1G + 2x1L + 7x1M + 3x2G + 4x2L + 5x2M + 5x3G + 2x3L + 3x3M

Paso 4:

x1G + x1L + x1M $\leq$ 75

x2G + x2L + x2M $\leq$ 50

x3G + x3L + x3M $\leq$ 60

x1G + x2G + x3G $\geq$ 60

x1L + x2L + x3L $\geq$ 45

x1M + x2M + x3M $\geq$ 60

In [17]:
c = np.array([
    5,
    2,
    7,
    3,
    4,
    5,
    5,
    2,
    3
])

Aub = np.array([
    [1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1],
    [-1, 0, 0, -1, 0, 0, -1, 0, 0],
    [0, -1, 0, 0, -1, 0, 0, -1, 0],
    [0, 0, -1, 0, 0, -1, 0, 0, -1]
])

bub = np.array([
    75,
    50,
    60,
    -60,
    -45,
    -60
])

opt.linprog(c, Aub, bub)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 470.0
              x: [ 1.000e+01  4.500e+01  0.000e+00  5.000e+01  0.000e+00
                   0.000e+00  0.000e+00  0.000e+00  6.000e+01]
            nit: 4
          lower:  residual: [ 1.000e+01  4.500e+01  0.000e+00  5.000e+01
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              6.000e+01]
                 marginals: [ 0.000e+00  0.000e+00  4.000e+00  0.000e+00
                              4.000e+00  4.000e+00  0.000e+00  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.0

Ejercicio 3.

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la siguiente tabla:

Producto	Tiempo [h]	Material [unidades de madera]
Mesas	3	6
Sillas	1	2
Libreros	4	5
Bases de cama	3	5
Las mesas se venden en $9000, las sillas en $3000, los libreros en $10000, y las bases de cama en $9000. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera, ¿qué les conviene construir durante una semana para maximizar su ganancia?

¿Cuántas horas trabaja cada quién? 40 el experimentado y 39 el aprendiz
¿Cuánto material se usa? 100 unidades
¿Cuál se el ingreso total si se vende todo lo fabricado? 176000

Paso 1: Maximizar ganancias

Paso 2: 

Experimentado
x1_m: mesas
x1_s: sillas
x1_l: libreros
x1_b: bases de cama

Aprendiz
x2_m: mesas
x2_s: sillas
x2_l: libreros
x2_b: bases de cama


Paso 3:
Función de costo
9000x1_m +9000x2_m + 30001x1_s + 3000x2_s + 10000x1_l + 10000x2_l + 9000x1_b + 9000x2_b

Paso 4:

3x1_m + 1x1_s + 4x1_l + 3x1_b  $\leq$ 40

4.5x2_m + 1.5x2_s + 6x2_l + 4.5x2_b $\leq$ 40

6x1_m + 7.2x2_m + 2x1_s + 2.2x2_s + 5x1_l + 6x2_l + 5x1_b + 6x2_b $\leq$ 100

In [44]:
c = np.array([
    -9000,
    -9000,
    -3000,
    -3000,
    -10000,
    -10000,
    -9000,
    -9000
])

Aub = np.array([
    [3, 0, 1, 0, 4, 0, 3, 0],
    [0, 4.5, 0, 1.5, 0, 6, 0, 4.5],
    [6, 7.2, 2, 2.4, 5, 6, 5, 6]
])

bub = ([
    40,
    40,
    100
])

sol = opt.linprog(c, Aub, bub, integrality = 1)
Aub @ sol.x

array([ 40.,  39., 100.])

2. La carpintería recibió una orden por 3 combos de mesa + 6 sillas.

¿Se puede cumplir la orden?
Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo y con el resto del material para maximizar su ganancia?
¿Cuántas horas trabaja cada quién?
¿Cuánto material se usa?
¿Cuál es el nuevo ingreso total?

In [48]:
c = np.array([
    -9000,
    -9000,
    -3000,
    -3000,
    -10000,
    -10000,
    -9000,
    -9000
])

Aub = np.array([
    [3, 0, 1, 0, 4, 0, 3, 0],
    [0, 4.5, 0, 1.5, 0, 6, 0, 4.5],
    [6, 7.2, 2, 2.4, 5, 6, 5, 6],
    [3, 3, 0, 0, 0, 0, 0, 0],
    [0, 0, 18, 18, 0, 0, 0, 0]
])

bub = ([
    40,
    40,
    100,
    3,
    18
])

sol = opt.linprog(c, Aub, bub, integrality = 1)
Aub @ sol.x

array([ 40.,  39., 100.,   0.,  18.])

Mónica hace aretes y cadenitas de joyería. Es tan buena, que todo lo que hace lo vende.

Le toma 30 minutos hacer un par de aretes y una hora hacer una cadenita, y como Mónica también es estudihambre, solo dispone de 10 horas a la semana para hacer las joyas. Por otra parte, el material que compra solo le alcanza para hacer 15 unidades (el par de aretes cuenta como unidad) de joyas por semana.

La utilidad que le deja la venta de las joyas es $\$15$ en cada par de aretes y $\$20$ en cada cadenita.

¿Cuántos pares de aretes y cuántas cadenitas debería hacer Mónica para maximizar su utilidad? 

15 aretes y 10 cadenitas

Paso 1: Maximizar ganancia

Paso 2: Cantidad de joyas

Paso 3: 15x (aretes) + 20y (cadenitas)

Paso 4: x + y $\leq$ 15

0.5x + y $\leq$ 10

In [53]:
c = np.array([
    -15,
    -20
])

Aub = np.array([
    [1, 1],
    [0.5, 1]
])

bub = ([
    15,
    10
])

sol = opt.linprog(c, Aub, bub)
Aub @ sol.x

array([15., 10.])

Una empresa tiene dos fábricas A y B. En ellas se fabrica un determinado producto, a razón de 500 y 400 unidades por día respectivamente. El producto ha de ser distribuido posteriormente a tres centros C, D y E, que requieren, respectivamente, 200, 300 y 400 unidades. Los costos de transportar cada unidad del producto desde cada fábrica a cada centro distribuidor son los indicados en la tabla siguiente:

Factoría	C	D	E	Fabricación (Unidades)
A	50 u.m	60 u.m	10 u.m	500 u
B	25 u.m	40 u.m	20 u.m	400 u
Demanda	200	300	400	
¿De qué manera deben organizar el transporte a fin de que los gastos sean mínimos?

Paso 1: Minimizar gastos

Paso 2: Cuántas unidades se mandan de cada planta

Paso 3: 50AC + 60AD + 10AE + 25BC + 40BD + 20BE

Paso 4: AC + AD + AE $\leq$ 500

BC + BD + BE $\leq$ 400

AC + BC $\leq$ 200

AD + BD $\leq$ 300

AE + BE $\leq$ 400

In [65]:
c = np.array([
    -50,
    -60,
    -10,
    -25,
    -40,
    -20
])

Aub = np.array([
    [50, 60, 10, 0, 0, 0],
    [0, 0, 0, 25, 40, 20],
    [50, 0, 0, 25, 0, 0],
    [0, 60, 0, 0, 40, 0],
    [0, 0, 10, 0, 0, 20]
])

bub = np.array([
    500,
    400,
    200,
    300,
    400
])

opt.linprog(c, Aub, bub)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -900.0
              x: [ 4.000e+00  5.000e+00 -0.000e+00  0.000e+00  0.000e+00
                   2.000e+01]
            nit: 4
          lower:  residual: [ 4.000e+00  5.000e+00 -0.000e+00  0.000e+00
                              0.000e+00  2.000e+01]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00]
                 marginals: [-1.000e+00 -1.000e+00 -0.00

El objetivo de este problema es determinar la mejor estrategia de inversión, dados diferentes tipos de bono, la máxima cantidad que puede ser invertida en cada bono, el porcentaje de retorno y los años de madurez. También hay una cantidad fija de dinero disponible ($\$750,000$). Por lo menos la mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez. Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono. Finalmente, hay otra restricción que no permite usar más de $35\%$ en bonos de alto riesgo.

Existen seis (6) opciones de inversión con las letras correspondientes $A_i$

1. $A_1$:(Tasa de retorno=$8.65\%$; Años para la madurez=11, Riesgo=Bajo)
1. $A_2$:(Tasa de retorno=$9.50\%$; Años para la madurez=10, Riesgo=Alto)
1. $A_3$:(Tasa de retorno=$10.00\%$; Años para la madurez=6, Riesgo=Alto)
1. $A_4$:(Tasa de retorno=$8.75\%$; Años para la madurez=10, Riesgo=Bajo)
1. $A_5$:(Tasa de retorno=$9.25\%$; Años para la madurez=7, Riesgo=Alto)
1. $A_6$:(Tasa de retorno=$9.00\%$; Años para la madurez=13, Riesgo=Bajo)

Lo que se quiere entonces es maximizar el retorno que deja la inversión.

Paso 1: Maximizar ganancia

Paso 2: Dinero invertido en cada fondo

Paso 3: 8.65A1 + 9.5A2 + 10A3 + 8.75A4 + 9.25A5 + 9A6

Paso 4: A1 + A2 +A3 + A4 + A5 + A6 $\leq$ 375000

A1 $\leq$ 187500

A2 $\leq$ 187500

A3 $\leq$ 187500

A4 $\leq$ 187500

A5 $\leq$ 187500

A6 $\leq$ 187500

A2 + A3 + A5 $\leq$ 262500

In [13]:
c = np.array([
    -8.65,
    -9.5,
    -10,
    -8.75
    -9.25,
    -9
])

Aub = np.array([
    [1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 1, 0]
])

bub = np.array([
    375000,
    187500,
    187500,
    187500,
    187500,
    187500,
    187500,
    262500
])

opt.linprog(c, Aub, bub)

ValueError: Invalid input for linprog: A_ub must have exactly two dimensions, and the number of columns in A_ub must be equal to the size of c